### ISSUE TITLE
Error if file is deleted but that change not committed

### ISSUE THREAD

**Issue by EdwardTheGreat** [mikepotjer/vfp-git-utils#1]
I deleted a file and then try to Save Time Stamps before committing that change, I get an error when the program tries to pull that files timestamp from windows.   It gets the file list from the Repository, but since the file is no longer in the directory, windows is returning a null.

FUNCTION GetRepoFileModifyDates

   at the very end of the function
loFolderItem = m.loFolder.ParseName( m.lcFileName )  && this returns .null.
taFileDateList[m.xx,2] = m.loFolderItem.ModifyDate       && which causes an error here

Note:  This only seems to occur if this is the first time I have ran Save TimeStamps on that directory.

**Comment by mikepotjer** [comment]
Edward,

Thanks for reporting this.  I've run into this a couple times, but was not able to pin down the conditions to reproduce it.  Your note about this only happening on the first time was especially helpful.  I can now reproduce it if:  
1. This is the first time the process is run - there is no timestamp file yet, and
2. The delete is not staged yet.

Thanks again,
MikeTheReasonablyCompetent

**Comment by EdwardTheGreat** [comment]
Dear Mike,

I am trying to create a small program or two for synching files from the
foxpro command window at the end of the day.

Something like:

set proc to c:\carpet\thor\tools\procs\thor_proc_gitutilities.prg addi

git   = Thor_Proc_GitUtilities()

cresult= []

oErr  = .null

?git.executecommand(oErr,[c:\carpet],[git commit -m WorkUpdate],cresult)

?git.executecommand(oErr,[c:\carpet],[git push],cresult)

Though I will probably have something to also show a list of the files that
are being committed and something maybe to handle the binary to text files
create by fox2bin.

Do you have something like this you use to commit/push your work?

THANK YOU VERY MUCH for you wonderful tool.   

Sincerely,

Eddie Caldwell

**Comment by mikepotjer** [comment]
Hi Eddie,

I'm more "hands-on" about commits (have been long before Git), so I never
did anything to automate commit/push.  I think code along the lines of what
wrote here should work, though.  Make sure you pass the oErr and cresult
parameters by reference.

I really like the free GUI tool SourceTree from Atlassian.  I do all my
commits, pushes, pulls, checkouts, etc. from that tool.  That's why I have
limited the VFP utilities I wrote to those tasks that are more or less
specific to VFP, and tedious or impossible to do with the existing Git
tools.

Thanks for the kind words, and for helping to make these utilities better.
Mike

Mike Potjer
